apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
- configmap.yaml
# - telemetry.yaml # DEBUG ONLY

patches:
- path: gateway.yaml
  target:
    kind: Gateway
labels:
- pairs:
    app.kubernetes.io/component: inference-gateway
    app.kubernetes.io/gateway: wide-ep-inference-gateway
    app.kubernetes.io/instance: wide-ep

