apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../kgateway
  - gateway-parameters.yaml

patches:
  - target:
      kind: Gateway
    patch: |
      - op: add
        path: /spec/infrastructure
        value:
          parametersRef:
            name: kgateway-params
            group: gateway.kgateway.dev
            kind: GatewayParameters
