apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: vllmpodmonigoring
  labels:
    app.kubernetes.io/name: vllmpodmonigoring
    app.kubernetes.io/part-of: google-cloud-managed-prometheus
spec:
  endpoints:
  - port: 8000
    scheme: http
    interval: 15s
    path: /metrics
  selector:
    matchLabels:
      app: qwen-model-32b
