apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../../recipes/gateway/kgateway
labels:
- pairs:
    app.kubernetes.io/instance: wide-ep
    app.kubernetes.io/gateway: llm-d-inference-gateway
    app.kubernetes.io/component: inference-gateway
